
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `results`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `results` (
  `Pid` int NOT NULL DEFAULT '0',
  `ChipCode` varchar(7) DEFAULT NULL,
  `Bib` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Cat` varchar(50) DEFAULT NULL,
  `SubCat` varchar(50) DEFAULT NULL,
  `Category` varchar(50) DEFAULT NULL,
  `Name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ChiName` varchar(50) DEFAULT NULL,
  `TeamNo` varchar(10) DEFAULT NULL,
  `Team` varchar(50) DEFAULT NULL,
  `Team1K` varchar(255) DEFAULT NULL,
  `Age` varchar(50) DEFAULT NULL,
  `Nationality` varchar(50) DEFAULT NULL,
  `Country` varchar(50) DEFAULT NULL,
  `SN` varchar(50) DEFAULT NULL,
  `Race` smallint DEFAULT '0',
  `Rank1Cat` int DEFAULT '0',
  `Rank1Mix` int DEFAULT '0',
  `Rank1Tot` int DEFAULT '0',
  `Rank1Team` int DEFAULT '0',
  `Rank2Team` int DEFAULT '0',
  `Lap` int DEFAULT '0',
  `BonusLap` int DEFAULT '0',
  `DQLap` smallint DEFAULT '0',
  `NR` tinyint(1) DEFAULT NULL,
  `DNS` tinyint(1) DEFAULT NULL,
  `DNF` tinyint(1) DEFAULT NULL,
  `DQ` tinyint(1) DEFAULT NULL,
  `Remark` varchar(50) DEFAULT NULL,
  `TimeTeam` int DEFAULT '0',
  `TimeGun` int DEFAULT '0',
  `TimeStart` int DEFAULT '0',
  `TimeFinish` int DEFAULT '0',
  `TimeCP1` int DEFAULT '0',
  `TimeStart1K` int DEFAULT '0',
  `TimeFinish1K` int DEFAULT '0',
  `TimeTeam1K` int DEFAULT '0',
  `TimeGun1K` int DEFAULT '0',
  `Sex` varchar(10) DEFAULT NULL,
  `Rank1Cat1K` int DEFAULT '0',
  `Rank1Mix1K` int DEFAULT '0',
  `Rank1Tot1K` int DEFAULT '0',
  `TimeCP2` int DEFAULT '0',
  `TimeCP3` int DEFAULT '0',
  `TimeCP4` int DEFAULT '0',
  `TimeCP5` int DEFAULT '0',
  `TimeCP6` int DEFAULT '0',
  `TimeCP7` int DEFAULT '0',
  `TimeCP8` int DEFAULT '0',
  `TimeCP9` int DEFAULT '0',
  `time0` int DEFAULT '0',
  `time1` int DEFAULT NULL,
  `time2` int DEFAULT NULL,
  `time3` int DEFAULT NULL,
  `time4` int DEFAULT NULL,
  `time5` int DEFAULT NULL,
  `time6` int DEFAULT NULL,
  `time7` int DEFAULT NULL,
  `time8` int DEFAULT NULL,
  `time9` int DEFAULT NULL,
  `time10` int DEFAULT NULL,
  `time11` int DEFAULT NULL,
  `time12` int DEFAULT NULL,
  `time13` int DEFAULT NULL,
  `time14` int DEFAULT NULL,
  `time15` int DEFAULT NULL,
  `time16` int DEFAULT NULL,
  `time17` int DEFAULT NULL,
  `time18` int DEFAULT NULL,
  `time19` int DEFAULT NULL,
  `time20` int DEFAULT NULL,
  `time21` int DEFAULT NULL,
  `time22` int DEFAULT NULL,
  `time23` int DEFAULT NULL,
  `time24` int DEFAULT NULL,
  `time25` int DEFAULT NULL,
  `time26` int DEFAULT NULL,
  `time27` int DEFAULT NULL,
  `time28` int DEFAULT NULL,
  `time29` int DEFAULT NULL,
  `time30` int DEFAULT NULL,
  `time31` int DEFAULT NULL,
  `time32` int DEFAULT NULL,
  `time33` int DEFAULT NULL,
  `time34` int DEFAULT NULL,
  `time35` int DEFAULT NULL,
  `time36` int DEFAULT NULL,
  `time37` int DEFAULT NULL,
  `time38` int DEFAULT NULL,
  `time39` int DEFAULT NULL,
  `time40` int DEFAULT NULL,
  `time41` int DEFAULT NULL,
  `time42` int DEFAULT NULL,
  `time43` int DEFAULT NULL,
  `time44` int DEFAULT NULL,
  `time45` int DEFAULT NULL,
  `time46` int DEFAULT NULL,
  `time47` int DEFAULT NULL,
  `time48` int DEFAULT NULL,
  `time49` int DEFAULT NULL,
  `time50` int DEFAULT NULL,
  `time51` int DEFAULT NULL,
  `time52` int DEFAULT NULL,
  `time53` int DEFAULT NULL,
  `time54` int DEFAULT NULL,
  `time55` int DEFAULT NULL,
  `time56` int DEFAULT NULL,
  `time57` int DEFAULT NULL,
  `time58` int DEFAULT NULL,
  `time59` int DEFAULT NULL,
  `time60` int DEFAULT NULL,
  `time61` int DEFAULT NULL,
  `time62` int DEFAULT NULL,
  `time63` int DEFAULT NULL,
  `time64` int DEFAULT NULL,
  `time65` int DEFAULT NULL,
  `time66` int DEFAULT NULL,
  `time67` int DEFAULT NULL,
  `time68` int DEFAULT NULL,
  `time69` int DEFAULT NULL,
  `time70` int DEFAULT NULL,
  `time71` int DEFAULT NULL,
  `time72` int DEFAULT NULL,
  `time73` int DEFAULT NULL,
  `time74` int DEFAULT NULL,
  `time75` int DEFAULT NULL,
  `time76` int DEFAULT NULL,
  `time77` int DEFAULT NULL,
  `time78` int DEFAULT NULL,
  `time79` int DEFAULT NULL,
  `time80` int DEFAULT NULL,
  `time81` int DEFAULT NULL,
  `time82` int DEFAULT NULL,
  `time83` int DEFAULT NULL,
  `time84` int DEFAULT NULL,
  `time85` int DEFAULT NULL,
  `time86` int DEFAULT NULL,
  `time87` int DEFAULT NULL,
  `time88` int DEFAULT NULL,
  `time89` int DEFAULT NULL,
  `time90` int DEFAULT NULL,
  `time91` int DEFAULT NULL,
  `time92` int DEFAULT NULL,
  `time93` int DEFAULT NULL,
  `time94` int DEFAULT NULL,
  `time95` int DEFAULT NULL,
  `time96` int DEFAULT NULL,
  `time97` int DEFAULT NULL,
  `time98` int DEFAULT NULL,
  `time99` int DEFAULT NULL,
  `time100` int DEFAULT NULL,
  `Bib_1` varchar(50) DEFAULT NULL,
  `No` int DEFAULT NULL,
  `Bib2` varchar(50) DEFAULT NULL,
  `Name2` varchar(50) DEFAULT NULL,
  `eventid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DOB` varchar(50) DEFAULT NULL,
  `Name3` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FS` tinyint DEFAULT NULL,
  `NSBF` tinyint DEFAULT NULL,
  `Distance` decimal(10,2) DEFAULT NULL,
  `NRIC` varchar(50) DEFAULT NULL,
  `company` varchar(50) DEFAULT NULL,
  `TimeCP10` int DEFAULT NULL,
  PRIMARY KEY (`Pid`),
  UNIQUE KEY `SYS_IDX_SYS_PK_10623_10624` (`Pid`),
  KEY `RESULTS_CHIPCODE` (`ChipCode`),
  KEY `RESULTS_PID` (`Pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `results_archive`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `results_archive` (
  `Pid` int NOT NULL DEFAULT '0',
  `ChipCode` varchar(7) DEFAULT NULL,
  `Bib` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Cat` varchar(50) DEFAULT NULL,
  `SubCat` varchar(50) DEFAULT NULL,
  `Category` varchar(50) DEFAULT NULL,
  `Name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ChiName` varchar(50) DEFAULT NULL,
  `TeamNo` varchar(10) DEFAULT NULL,
  `Team` varchar(50) DEFAULT NULL,
  `Team1K` varchar(255) DEFAULT NULL,
  `Age` varchar(50) DEFAULT NULL,
  `Nationality` varchar(50) DEFAULT NULL,
  `Country` varchar(50) DEFAULT NULL,
  `SN` varchar(50) DEFAULT NULL,
  `Race` smallint DEFAULT '0',
  `Rank1Cat` int DEFAULT '0',
  `Rank1Mix` int DEFAULT '0',
  `Rank1Tot` int DEFAULT '0',
  `Rank1Team` int DEFAULT '0',
  `Rank2Team` int DEFAULT '0',
  `Lap` int DEFAULT '0',
  `BonusLap` int DEFAULT '0',
  `DQLap` smallint DEFAULT '0',
  `NR` tinyint(1) DEFAULT NULL,
  `DNS` tinyint(1) DEFAULT NULL,
  `DNF` tinyint(1) DEFAULT NULL,
  `DQ` tinyint(1) DEFAULT NULL,
  `Remark` varchar(50) DEFAULT NULL,
  `TimeTeam` int DEFAULT '0',
  `TimeGun` int DEFAULT '0',
  `TimeStart` int DEFAULT '0',
  `TimeFinish` int DEFAULT '0',
  `TimeCP1` int DEFAULT '0',
  `TimeStart1K` int DEFAULT '0',
  `TimeFinish1K` int DEFAULT '0',
  `TimeTeam1K` int DEFAULT '0',
  `TimeGun1K` int DEFAULT '0',
  `Sex` varchar(10) DEFAULT NULL,
  `Rank1Cat1K` int DEFAULT '0',
  `Rank1Mix1K` int DEFAULT '0',
  `Rank1Tot1K` int DEFAULT '0',
  `TimeCP2` int DEFAULT '0',
  `TimeCP3` int DEFAULT '0',
  `TimeCP4` int DEFAULT '0',
  `TimeCP5` int DEFAULT '0',
  `TimeCP6` int DEFAULT '0',
  `TimeCP7` int DEFAULT '0',
  `TimeCP8` int DEFAULT '0',
  `TimeCP9` int DEFAULT '0',
  `time0` int DEFAULT '0',
  `time1` int DEFAULT NULL,
  `time2` int DEFAULT NULL,
  `time3` int DEFAULT NULL,
  `time4` int DEFAULT NULL,
  `time5` int DEFAULT NULL,
  `time6` int DEFAULT NULL,
  `time7` int DEFAULT NULL,
  `time8` int DEFAULT NULL,
  `time9` int DEFAULT NULL,
  `time10` int DEFAULT NULL,
  `time11` int DEFAULT NULL,
  `time12` int DEFAULT NULL,
  `time13` int DEFAULT NULL,
  `time14` int DEFAULT NULL,
  `time15` int DEFAULT NULL,
  `time16` int DEFAULT NULL,
  `time17` int DEFAULT NULL,
  `time18` int DEFAULT NULL,
  `time19` int DEFAULT NULL,
  `time20` int DEFAULT NULL,
  `time21` int DEFAULT NULL,
  `time22` int DEFAULT NULL,
  `time23` int DEFAULT NULL,
  `time24` int DEFAULT NULL,
  `time25` int DEFAULT NULL,
  `time26` int DEFAULT NULL,
  `time27` int DEFAULT NULL,
  `time28` int DEFAULT NULL,
  `time29` int DEFAULT NULL,
  `time30` int DEFAULT NULL,
  `time31` int DEFAULT NULL,
  `time32` int DEFAULT NULL,
  `time33` int DEFAULT NULL,
  `time34` int DEFAULT NULL,
  `time35` int DEFAULT NULL,
  `time36` int DEFAULT NULL,
  `time37` int DEFAULT NULL,
  `time38` int DEFAULT NULL,
  `time39` int DEFAULT NULL,
  `time40` int DEFAULT NULL,
  `time41` int DEFAULT NULL,
  `time42` int DEFAULT NULL,
  `time43` int DEFAULT NULL,
  `time44` int DEFAULT NULL,
  `time45` int DEFAULT NULL,
  `time46` int DEFAULT NULL,
  `time47` int DEFAULT NULL,
  `time48` int DEFAULT NULL,
  `time49` int DEFAULT NULL,
  `time50` int DEFAULT NULL,
  `time51` int DEFAULT NULL,
  `time52` int DEFAULT NULL,
  `time53` int DEFAULT NULL,
  `time54` int DEFAULT NULL,
  `time55` int DEFAULT NULL,
  `time56` int DEFAULT NULL,
  `time57` int DEFAULT NULL,
  `time58` int DEFAULT NULL,
  `time59` int DEFAULT NULL,
  `time60` int DEFAULT NULL,
  `time61` int DEFAULT NULL,
  `time62` int DEFAULT NULL,
  `time63` int DEFAULT NULL,
  `time64` int DEFAULT NULL,
  `time65` int DEFAULT NULL,
  `time66` int DEFAULT NULL,
  `time67` int DEFAULT NULL,
  `time68` int DEFAULT NULL,
  `time69` int DEFAULT NULL,
  `time70` int DEFAULT NULL,
  `time71` int DEFAULT NULL,
  `time72` int DEFAULT NULL,
  `time73` int DEFAULT NULL,
  `time74` int DEFAULT NULL,
  `time75` int DEFAULT NULL,
  `time76` int DEFAULT NULL,
  `time77` int DEFAULT NULL,
  `time78` int DEFAULT NULL,
  `time79` int DEFAULT NULL,
  `time80` int DEFAULT NULL,
  `time81` int DEFAULT NULL,
  `time82` int DEFAULT NULL,
  `time83` int DEFAULT NULL,
  `time84` int DEFAULT NULL,
  `time85` int DEFAULT NULL,
  `time86` int DEFAULT NULL,
  `time87` int DEFAULT NULL,
  `time88` int DEFAULT NULL,
  `time89` int DEFAULT NULL,
  `time90` int DEFAULT NULL,
  `time91` int DEFAULT NULL,
  `time92` int DEFAULT NULL,
  `time93` int DEFAULT NULL,
  `time94` int DEFAULT NULL,
  `time95` int DEFAULT NULL,
  `time96` int DEFAULT NULL,
  `time97` int DEFAULT NULL,
  `time98` int DEFAULT NULL,
  `time99` int DEFAULT NULL,
  `time100` int DEFAULT NULL,
  `Bib_1` varchar(50) DEFAULT NULL,
  `No` int DEFAULT NULL,
  `Bib2` varchar(50) DEFAULT NULL,
  `Name2` varchar(50) DEFAULT NULL,
  `eventid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DOB` varchar(50) DEFAULT NULL,
  `Name3` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FS` tinyint DEFAULT NULL,
  `NSBF` tinyint DEFAULT NULL,
  `Distance` decimal(10,2) DEFAULT NULL,
  `NRIC` varchar(50) DEFAULT NULL,
  `company` varchar(50) DEFAULT NULL,
  `TimeCP10` int DEFAULT NULL,
  KEY `RESULTS_ARCHIVE_CHIPCODE` (`ChipCode`),
  KEY `RESULTS_ARCHIVE_EVENTID` (`eventid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_event`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_event` (
  `id` varchar(36) NOT NULL,
  `name` varchar(200) NOT NULL,
  `event_dt` date DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `country` varchar(100) NOT NULL,
  `weather` varchar(200) DEFAULT NULL,
  `archived` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_event_cat`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_event_cat` (
  `event_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `cat` varchar(100) NOT NULL,
  `category` varchar(100) NOT NULL,
  `distance` decimal(10,0) NOT NULL,
  `race` varchar(100) NOT NULL,
  `gender` varchar(100) NOT NULL,
  `TimeGun` int DEFAULT NULL,
  `TimeGun1` int DEFAULT NULL,
  `TimeGun2` int DEFAULT NULL,
  `TimeGun3` int DEFAULT NULL,
  `TimeGun4` int DEFAULT NULL,
  `TimeGun5` int DEFAULT NULL,
  `TimeGun6` int DEFAULT NULL,
  `CPLIST` varchar(200) DEFAULT NULL,
  `is_Lap` tinyint DEFAULT NULL,
  `racemode` varchar(100) DEFAULT NULL,
  `cat_id` int DEFAULT NULL,
  `Top` int DEFAULT NULL,
  `is_Live` int DEFAULT NULL,
  `is_result` int DEFAULT NULL,
  `top_prize` decimal(10,0) DEFAULT '0',
  KEY `t_event_cat_t_event_FK` (`event_id`),
  CONSTRAINT `t_event_cat_t_event_FK` FOREIGN KEY (`event_id`) REFERENCES `t_event` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_org`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_org` (
  `id` varchar(36) NOT NULL,
  `org_name` varchar(200) NOT NULL,
  `owner` varchar(200) NOT NULL,
  `is_active` tinyint NOT NULL,
  `ownercontact` varchar(100) DEFAULT NULL,
  `owneremail` varchar(100) DEFAULT NULL,
  `dt_create` date DEFAULT NULL,
  `dt_update` date DEFAULT NULL,
  `alias` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_org_event`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_org_event` (
  `id` varchar(36) NOT NULL,
  `org_id` varchar(36) NOT NULL,
  `event_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `t_org_event_t_org_fk` (`org_id`),
  KEY `t_org_event_t_event_FK` (`event_id`),
  CONSTRAINT `t_org_event_t_event_FK` FOREIGN KEY (`event_id`) REFERENCES `t_event` (`id`),
  CONSTRAINT `t_org_event_t_org_fk` FOREIGN KEY (`org_id`) REFERENCES `t_org` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_org_contract`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_org_contract` (
  `id` varchar(36) NOT NULL,
  `org_id` varchar(36) NOT NULL,
  `description` varchar(100) NOT NULL,
  `contract_start_date` date NOT NULL,
  `contract_end_date` date NOT NULL,
  `billing_duration` varchar(100) NOT NULL,
  `status` varchar(100) NOT NULL,
  `is_active` tinyint NOT NULL,
  KEY `t_org_contract_t_org_fk` (`org_id`),
  CONSTRAINT `t_org_contract_t_org_fk` FOREIGN KEY (`org_id`) REFERENCES `t_org` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_org_user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_org_user` (
  `id` varchar(36) NOT NULL,
  `username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `org_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `session_id` varchar(100) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `session_expiry_time` datetime DEFAULT NULL,
  `full_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Role` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `t_results`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_results` (
  `EventId` varchar(50) DEFAULT NULL,
  `Pid` int NOT NULL DEFAULT '0',
  `ChipCode` varchar(7) DEFAULT NULL,
  `Bib` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Cat` varchar(50) DEFAULT NULL,
  `SubCat` varchar(50) DEFAULT NULL,
  `Category` varchar(50) DEFAULT NULL,
  `Name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ChiName` varchar(50) DEFAULT NULL,
  `TeamNo` varchar(10) DEFAULT NULL,
  `Team` varchar(50) DEFAULT NULL,
  `Team1K` varchar(255) DEFAULT NULL,
  `Age` varchar(50) DEFAULT NULL,
  `Nationality` varchar(50) DEFAULT NULL,
  `Country` varchar(50) DEFAULT NULL,
  `SN` varchar(50) DEFAULT NULL,
  `Race` smallint DEFAULT '0',
  `Rank1Cat` int DEFAULT '0',
  `Rank1Mix` int DEFAULT '0',
  `Rank1Tot` int DEFAULT '0',
  `Rank1Team` int DEFAULT '0',
  `Rank2Team` int DEFAULT '0',
  `Lap` int DEFAULT '0',
  `BonusLap` int DEFAULT '0',
  `DQLap` smallint DEFAULT '0',
  `NR` tinyint(1) DEFAULT NULL,
  `DNS` tinyint(1) DEFAULT NULL,
  `DNF` tinyint(1) DEFAULT NULL,
  `DQ` tinyint(1) DEFAULT NULL,
  `FS` tinyint(1) DEFAULT NULL,
  `NSBF` tinyint(1) DEFAULT NULL,
  `Remark` varchar(50) DEFAULT NULL,
  `TimeTeam` int DEFAULT '0',
  `TimeGun` int DEFAULT '0',
  `TimeStart` int DEFAULT '0',
  `TimeFinish` int DEFAULT '0',
  `TimeCP1` int DEFAULT '0',
  `TimeStart1K` int DEFAULT '0',
  `TimeFinish1K` int DEFAULT '0',
  `TimeTeam1K` int DEFAULT '0',
  `TimeGun1K` int DEFAULT '0',
  `Sex` varchar(10) DEFAULT NULL,
  `Rank1Cat1K` int DEFAULT '0',
  `Rank1Mix1K` int DEFAULT '0',
  `Rank1Tot1K` int DEFAULT '0',
  `TimeCP2` int DEFAULT '0',
  `TimeCP3` int DEFAULT '0',
  `TimeCP4` int DEFAULT '0',
  `TimeCP5` int DEFAULT '0',
  `TimeCP6` int DEFAULT '0',
  `TimeCP7` int DEFAULT '0',
  `TimeCP8` int DEFAULT '0',
  `TimeCP9` int DEFAULT '0',
  `TimeCP10` int DEFAULT '0',
  `time1` int DEFAULT '0',
  `time2` int DEFAULT '0',
  `time3` int DEFAULT '0',
  `time4` int DEFAULT '0',
  `time5` int DEFAULT '0',
  `time6` int DEFAULT '0',
  `time7` int DEFAULT '0',
  `time8` int DEFAULT '0',
  `time9` int DEFAULT '0',
  `time10` int DEFAULT '0',
  `time11` int DEFAULT '0',
  `time12` int DEFAULT '0',
  `time13` int DEFAULT '0',
  `time14` int DEFAULT '0',
  `time15` int DEFAULT '0',
  `time16` int DEFAULT '0',
  `time17` int DEFAULT '0',
  `time18` int DEFAULT '0',
  `time19` int DEFAULT '0',
  `time20` int DEFAULT '0',
  `time21` int DEFAULT '0',
  `time22` int DEFAULT '0',
  `time23` int DEFAULT '0',
  `time24` int DEFAULT '0',
  `time25` int DEFAULT '0',
  `time26` int DEFAULT '0',
  `time27` int DEFAULT '0',
  `time28` int DEFAULT '0',
  `time29` int DEFAULT '0',
  `time30` int DEFAULT '0',
  `time31` int DEFAULT '0',
  `time32` int DEFAULT '0',
  `time33` int DEFAULT '0',
  `time34` int DEFAULT '0',
  `time35` int DEFAULT '0',
  `time36` int DEFAULT '0',
  `time37` int DEFAULT '0',
  `time38` int DEFAULT '0',
  `time39` int DEFAULT '0',
  `time40` int DEFAULT '0',
  `time41` int DEFAULT '0',
  `time42` int DEFAULT '0',
  `time43` int DEFAULT '0',
  `time44` int DEFAULT '0',
  `time45` int DEFAULT '0',
  `time46` int DEFAULT '0',
  `time47` int DEFAULT '0',
  `time48` int DEFAULT '0',
  `time49` int DEFAULT '0',
  `time50` int DEFAULT '0',
  `time51` int DEFAULT '0',
  `time52` int DEFAULT '0',
  `time53` int DEFAULT '0',
  `time54` int DEFAULT '0',
  `time55` int DEFAULT '0',
  `time56` int DEFAULT '0',
  `time57` int DEFAULT '0',
  `time58` int DEFAULT '0',
  `time59` int DEFAULT '0',
  `time60` int DEFAULT '0',
  `time61` int DEFAULT '0',
  `time62` int DEFAULT '0',
  `time63` int DEFAULT '0',
  `time64` int DEFAULT '0',
  `time65` int DEFAULT '0',
  `time66` int DEFAULT '0',
  `time67` int DEFAULT '0',
  `time68` int DEFAULT '0',
  `time69` int DEFAULT '0',
  `time70` int DEFAULT '0',
  `time71` int DEFAULT '0',
  `time72` int DEFAULT '0',
  `time73` int DEFAULT '0',
  `time74` int DEFAULT '0',
  `time75` int DEFAULT '0',
  `time76` int DEFAULT '0',
  `time77` int DEFAULT '0',
  `time78` int DEFAULT '0',
  `time79` int DEFAULT '0',
  `time80` int DEFAULT '0',
  `time81` int DEFAULT '0',
  `time82` int DEFAULT '0',
  `time83` int DEFAULT '0',
  `time84` int DEFAULT '0',
  `time85` int DEFAULT '0',
  `time86` int DEFAULT '0',
  `time87` int DEFAULT '0',
  `time88` int DEFAULT '0',
  `time89` int DEFAULT '0',
  `time90` int DEFAULT '0',
  `time91` int DEFAULT '0',
  `time92` int DEFAULT '0',
  `time93` int DEFAULT '0',
  `time94` int DEFAULT '0',
  `time95` int DEFAULT '0',
  `time96` int DEFAULT '0',
  `time97` int DEFAULT '0',
  `time98` int DEFAULT '0',
  `time99` int DEFAULT '0',
  `time100` int DEFAULT '0',
  `Bib_1` varchar(50) DEFAULT NULL,
  `No` int DEFAULT NULL,
  `Bib2` varchar(50) DEFAULT NULL,
  `Name2` varchar(50) DEFAULT NULL,
  `DOB` varchar(50) DEFAULT NULL,
  `Name3` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Distance` decimal(10,2) DEFAULT NULL,
  `NRIC` varchar(50) DEFAULT NULL,
  `company` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`Pid`),
  UNIQUE KEY `SYS_IDX_SYS_PK_10623_10624` (`Pid`),
  KEY `RESULTS_CHIPCODE` (`ChipCode`),
  KEY `RESULTS_PID` (`Pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `servicelog`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `servicelog` (
  `Query` varchar(100) DEFAULT NULL,
  `Query_Text` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Log_Time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


-- Procedures
DELIMITER $$

-- Missing procedure DDL (privileges?): P_LEADERBOARD_REPORT

-- Missing procedure: generate_marathon_result

-- Missing procedure: get_marathon_results

-- Missing procedure DDL (privileges?): P_ASSIGN_RANK1CAT

-- Missing procedure DDL (privileges?): P_ASSIGN_RANK1TOT

-- Missing procedure DDL (privileges?): P_ASSIGN_RANK1MIX

-- Missing procedure DDL (privileges?): P_STATISTIC_00_REPORT

-- Missing procedure DDL (privileges?): P_STATISTIC_00_REGLIST

-- Missing procedure DDL (privileges?): P_STATISTIC_01_STARTLIST

-- Missing procedure DDL (privileges?): P_STATISTIC_02_DNS

-- Missing procedure DDL (privileges?): P_STATISTIC_03_FINISHED

-- Missing procedure DDL (privileges?): P_STATISTIC_04_DNF

-- Missing procedure DDL (privileges?): P_STATISTIC_05_FS

-- Missing procedure DDL (privileges?): P_STATISTIC_06_NSBF

-- Missing procedure DDL (privileges?): P_STATISTIC_07_DQ

-- Missing procedure DDL (privileges?): P_DUMMY_REPORT

-- Missing procedure DDL (privileges?): P_DUMMY_REPORT_CLEAR
DELIMITER ;
